# Generated by Django 3.1 on 2020-09-28 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(default='miscellaneous', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 10, 2, 19, 42, 15, 588059)),
        ),
    ]
