# Generated by Django 3.1 on 2020-09-28 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200928_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_bid',
            new_name='largest_bid',
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 10, 2, 21, 45, 40, 444308)),
        ),
    ]
